### ISSUE TITLE
Unpredictable timezone

### ISSUE THREAD

**Issue by szepeviktor** [merge-org/wp-plugin-merge-org-sort#6]
https://github.com/merge-org/wp-plugin-merge-org-sort/blob/6dc194da34a0a41a162b3b90392102aa05ac4fc8/src/Service/SalesIncrementer.php#L20

Using PHP built-in functions will use PHP timezone.
Please consider using WC date functions.

**Comment by kristos80** [comment]
Hi @szepeviktor and thank you so much for your interest in our custom plugin --which is WIP (and at a very early stage)

I saw the rest of the issues you opened and I really love your enthusiasm! 

All of the previous issues actually make some sense (in one way or another), but this specific one really needs to be operated by the PHP `date` function in order to be relative to the other all other dates used in the context of the plugin.

Since we don't need to be super critical regarding date comparisons, as as I said before everything is relative, `date` actually makes more sense other than anything else.

Thanks again though
